version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  ignore:
      # We don't want to update uswds - this update will be handled manually as-needed
    - dependency-name: "uswds"
      # We don't want packages to update between major versions. Patch and minor only. Hopefully ensuring not breaking changes.
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  open-pull-requests-limit: 10
  labels:
  - 'type: dependencies'