version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  ignore:
    - dependency-name: "14-alpine"
  open-pull-requests-limit: 10
  labels:
  - 'type: dependencies'
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  ignore:
    - dependency-name: "uswds"
  open-pull-requests-limit: 10
  labels:
  - 'type: dependencies'