comment:
  on-update: recreate
  header: |
    View Storybook deploy: {{ branchUrl }}

  footer: |
    ---
    Automated comment created by [PR Commenter](https://github.com/exercism/pr-commenter-action) :robot:.
