comment:
  on-update: recreate
  header: |
    📖 Storybook Branch Deploy

  footer: |
    ---
    Automated comment created by [PR Commenter](https://github.com/exercism/pr-commenter-action) :robot:.

  snippets:
    - id: storybook-branch
      files: '*.tsx'
      body: Check out your component in Storybook - {{ branchUrl }}
