pull_request_rules:
  - name: Automatic queue on >=1 or >=2 approvals   # rule for Auto-Queueing PRs to Default Merge Queue
    conditions:
      - author!=dependabot[bot] # if author is not dependabot
      - or:
        - and:
          - "#approved-reviews-by>=2"
          - label="needs:\ 2 appeng approvals"
        - and:
          - "#approved-reviews-by>=1"
          - label!="needs:\ 2 appeng approvals"
      - schedule=Mon-Fri 09:00-19:00[America/Los_Angeles] # schedule the PRs to be queued during PST work hours
    actions:
      queue:
        name: default

  - name: automatic merge from dependabot # rule for Auto-Queueing PRs to Dependabot Merge Queue
    conditions:
      - "#approved-reviews-by >= 1"
      - or:
        - author=dependabot[bot]
        - author=renovate[bot]
    actions:
      queue:
        name: dependabot-merge-queue

queue_rules:
  - name: default # default merge queue
    queue_conditions:
      - "#approved-reviews-by >= 1"
    merge_method: squash

  - name: dependabot-merge-queue # dependabot merge queue
    queue_conditions:
      - "#approved-reviews-by >= 1"
    merge_method: squash
