pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash

queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by >= 1"
    merge_method: squash