version: '3.8'

services:
  redis:
    container_name: portal_redis
    image: redis:6.0
    ports:
      - '6379:6379'

  mongo:
    container_name: mongo
    image: mongo:4.0.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dev
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - '8888:8081'
    depends_on:
      - mongo

volumes:
  mongodb_data_container:
