
# Overrides for e2e on local
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.12
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cypress-e2e
    ports:
      - '27017:27017'