#Overrides for e2e testing
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: e2e
    container_name: app
    restart: always
    ports:
      - '3000:3000'
    environment:
      SAML_ISSUER: ussf-portal-client
      SAML_IDP_METADATA_URL: http://idp:8080/simplesaml/saml2/idp/metadata.php
      REDIS_URL: redis://portal_redis:6379
      MONGO_URL: mongodb://mongo:27017
      MONGODB_DB: cypress-e2e
      SESSION_SECRET: thisvaluecanbeanythingitisonlyforlocaldevelopment
    stdin_open: true
    depends_on:
      - mongo
      - redis
      - idp
      - cms

  mongo:
    container_name: mongo
    image: mongo:4.0.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cypress-e2e
    ports:
      - '27017:27017'

  cms:
    container_name: keystone-cms
    build:
      context: ../ussf-portal-cms
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      SESSION_SECRET: thisvaluecanbeanythingitisonlyforlocaldevelopment
      DATABASE_URL: postgres://keystone:keystonecms@keystone-db:5432/keystone
      TEST_USERNAME: Admin
      TEST_PASSWORD: adminpassword
      TEST_EMAIL: admin@example.com
      PORTAL_URL: app:3000
    depends_on:
      - keystone-db
      - redis
