version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-gh
      target: e2e
      args:
        BUILD: localbuild
    container_name: client
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://portal_redis:6379
      - MONGO_URL=mongodb://mongo:27017
      - SAML_IDP_METADATA_URL=http://idp:8080/simplesaml/saml2/idp/metadata.php
      - KEYSTONE_URL=http://keystone-cms:3001
      - KEYSTONE_PUBLIC_URL=http://localhost:3001
      - PERSONNEL_API_URL=http://personnel-api:4000
        # same as set by .envrc
      - SAML_ISSUER
      - SESSION_SECRET
      - SESSION_DOMAIN
      - MONGODB_DB
      - MONGO_HOST
      - MONGO_USER
      - MONGO_PASSWORD
      - LAUNCHDARKLY_SDK_CLIENT_SIDE_ID
      - MATOMO_URL
      - MATOMO_SITE_ID
    stdin_open: true
    depends_on:
      - mongo
      - redis
      - idp
