version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: http://localhost:3000
    container_name: app
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGODB_DB: cypress-e2e
    stdin_open: true
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.0.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cypress-e2e
    ports:
      - '27017:27017'
