version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'

  idp:
    container_name: test-saml-idp
    image: kristophjunge/test-saml-idp
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: ussf-portal-client
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:3000/api/login
    volumes:
      - ./users.php:/var/www/simplesamlphp/config/authsources.php
