FROM node:14.18.2-slim
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.

RUN apt-get update \
    && apt-get -y install openssl libc6 git
WORKDIR /app

# Install and cache dependencies
COPY package.json yarn.lock ./

# Copy files that embedded keystone requires
COPY ./src/cms/schema.ts ./src/cms/schema.ts
COPY ./cms.db .
COPY keystone.ts .

# Copy script for uswds assets
COPY scripts/copy_uswds_assets.sh scripts/copy_uswds_assets.sh

RUN yarn install --frozen-lockfile

# Copy app code
COPY . .

EXPOSE 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["yarn", "dev"]