version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb_data_container:
