version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGODB_DB=dev
    stdin_open: true
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.0.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dev
      # MONGO_INITDB_ROOT_USERNAME: admin-local
      # MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin-local
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: mysecretpassword
    #   ME_CONFIG_MONGODB_URL: mongodb://admin-local:mysecretpassword@mongo:27017/
    ports:
      - '8888:8081'
    depends_on:
      - mongo
volumes:
  mongodb_data_container:
