# Overrides for e2e testing
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: e2e
    container_name: app
    image: "${IMAGE_TAG}"
    restart: always
    ports:
      - '3000:3000'
    environment:
      SAML_ISSUER: ussf-portal-client
      SAML_IDP_METADATA_URL: http://idp:8080/simplesaml/saml2/idp/metadata.php
      REDIS_URL: redis://portal_redis:6379
      MONGO_URL: mongodb://mongo:27017
      MONGODB_DB: cypress-e2e
      SESSION_SECRET: thisvaluecanbeanythingitisonlyforlocaldevelopment
    stdin_open: true
    depends_on:
      - mongo
      - redis
      - idp

  # CMS app
  cms:
    build:
      context: ../ussf-portal-cms/
      dockerfile: Dockerfile
      target: e2e
    container_name: cms
    restart: always
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      DATABASE_URL: postgres://keystone:keystonecms@keystone-db:5432/keystone
      REDIS_URL: redis://portal_redis:6379
      SESSION_SECRET: thisvaluecanbeanythingitisonlyforlocaldevelopment
      SESSION_DOMAIN: localhost
    stdin_open: true
    depends_on:
      - keystone-db
      - redis
      - idp

  mongo:
    container_name: mongo
    image: mongo:4.0.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cypress-e2e
    ports:
      - '27017:27017'
