version: '3.8'

services:
  redis:
    container_name: portal_redis
    image: redis:6.0
    ports:
      - '6379:6379'

  mongo:
    container_name: mongo
    image: mongo:4.0.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dev
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - '8888:8081'
    depends_on:
      - mongo

  idp:
    container_name: test-saml-idp
    image: kristophjunge/test-saml-idp
    restart: always
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: ussf-portal-client
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:3000/api/auth/login
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:3000/api/auth/logout/callback
    volumes:
      - ./users.php:/var/www/simplesamlphp/config/authsources.php

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  matomo:
    # https://github.com/bitnami/bitnami-docker-matomo
    image: docker.io/bitnami/matomo:4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MATOMO_WEBSITE_NAME=ussf-portal
      - MATOMO_WEBSITE_HOST=http://localhost:3000
    volumes:
      - 'matomo_data:/bitnami/matomo'
    depends_on:
      - mariadb

  keystone-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=keystonecms
      - POSTGRES_USER=keystone
      - POSTGRES_DB=keystone
    ports:
      - '5432:5432'
    volumes:
      - cms_data:/var/lib/postgresql/data/

volumes:
  mongodb_data_container:
  cms_data:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
