name: Keystone CMS Docker Build Cache and Save Artifact

on:
  workflow_dispatch:

jobs:
  build-and-cache-keystone-cms:
      uses: USSF-ORBIT/ussf-portal/.github/workflows/reusable-docker-cache-keystone-cms.yml@main
