name: Cypress E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: '14.18.1'

      - name: Check out repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2

      - name: Docker compose
        run: docker-compose -f docker-compose.e2e.yml up -d

      - name: Cypress run
        uses: cypress-io/github-action@2113e5bc19c45979ba123df6e07256d2aaba9a33 # renovate: tag=v2.11.7
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        with:
          install-command: yarn cypress:install --frozen-lockfile
          working-directory: e2e

      - name: Upload screenshots
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos

      - name: Upload reports
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        if: always()
        with:
          name: cypress-reports
          path: e2e/cypress/reports
