name: Cypress E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2
        with:
          node-version: '14.18.1'

      - name: Check out repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Docker compose
        run: docker-compose -f docker-compose.services.yml -f docker-compose.e2e.yml up -d --build

      - name: Cypress run
        uses: cypress-io/github-action@90f0f494f47dd0a22ac4759978de892d3e3fd340 # tag=v3.0.2
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        with:
          install-command: yarn install --frozen-lockfile
          working-directory: e2e

      - name: Upload screenshots
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos

      - name: Upload reports
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
        if: always()
        with:
          name: cypress-reports
          path: e2e/cypress/reports
