name: Cypress E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: '14.19.1'

      - name: Check out repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          path: ./ussf-portal-client

      - name: Check out cms
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: USSF-ORBIT/ussf-portal-cms
          path: ./ussf-portal-cms

      - name: Build image for testing
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $IMAGE_TAG --target e2e .
        working-directory: ./ussf-portal-client

      - name: Docker compose
        run: docker-compose -f docker-compose.e2e.yml up -d
        env:
          IMAGE_TAG: ${{ github.sha }}

      - name: Cypress run
        uses: cypress-io/github-action@16aacf8ea6a67e5e5d907d34bc3be8ad0e6e979f # tag=v3.0.3
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        with:
          install-command: yarn install --frozen-lockfile
          working-directory: e2e

      - name: Upload screenshots
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos

      - name: Upload reports
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: always()
        with:
          name: cypress-reports
          path: e2e/cypress/reports
