on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    uses: USSF-ORBIT/ussf-portal/.github/workflows/reusable-release-please.yml@sc-2354/add-reusable-release-please
    with:
      release-type: node
      package-name: ussf-portal-client
