name: Deploy Storybook to Github Pages

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    steps:
      - name: Check out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Read Node.js version from package.json
        run: echo "nodeVersion=$(node -p "require('./package.json').engines.node")" >> $GITHUB_OUTPUT
        id: engines

      - name: Set up node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ steps.yarn-cache-dir-path.outputs.dir }}

      # The yarn cache is not node_modules
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate GraphQL types
        run: yarn generate

      - name: Deploy Storybook to Github page
        run: yarn storybook:deploy --ci --source-branch=main
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
