name: Deploy Storybook to Github Pages

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Read Node.js version from package.json
        run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
        id: engines

      - name: Set up node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # The yarn cache is not node_modules
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate GraphQL types
        run: yarn generate

      - name: Deploy Storybook to Github page
        run: yarn storybook:deploy --ci --source-branch=main
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
