name: Storybook Branch Deploy
env:
  NETLIFY_BRANCH_DEPLOY: ${{ secrets.NETLIFY_BRANCH_DEPLOY }}
  BRANCH_NAME: ${{github.head_ref}}
on:
  push:
    branches:
      - storybook-*
      - ci-storybook-netlify-branch-deploy
jobs:
  storybook-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Branch name
        run: echo running on ${GITHUB_REF##*/}

      - name: Call Netlify build
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/$NETLIFY_BRANCH_DEPLOY\?trigger_branch\=${GITHUB_REF##*/}\&trigger_title\=triggered+by+github+workflow
