name: Netlify Storybook Branch Deploy

on:
  pull_request:
    types:
      - labeled

jobs:
  storybook-branch-deploy:
    runs-on: ubuntu-latest
    if: github.event.label.name == format('type{0} storybook component', ':')
    steps:
      - name: Check out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Trigger Netlify build
        id: deploy-storybook-to-netlify
        uses: jsmrcaga/action-netlify-deploy@4fcfeb85d65e4b5dd117b7a495bd269448f25e20 # v1.8.2
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: false
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: 'storybook-static'
          build_command: 'yarn storybook:build'
          node_version: 14.19.1
        continue-on-error: false

      - name: Post Storybook URL
        uses: thollander/actions-comment-pull-request@632cf9ce90574d125be56b5f3405cda41a84e2fd # v2.3.1
        with:
          GITHUB_TOKEN: '${{github.token}}'
          message: '🎉 View this branch in Storybook - [${{ steps.deploy-storybook-to-netlify.outputs.NETLIFY_PREVIEW_URL }}](${{ steps.deploy-storybook-to-netlify.outputs.NETLIFY_PREVIEW_URL }})'
